create database customer_behavior_db;
use customer_behavior_db;

select * from customer limit 20;

-- Q1. what is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue 
from customer
group by 1;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
from customer
where discount_applied ='yes' and purchase_amount >=(select avg(purchase_amount) as average
from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as review_rate 
from customer 
group by 1
order by 2 desc
limit 5;

-- Q4: Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type ,round(avg(purchase_amount),2) as Avg_purchase
from customer
where shipping_type in ('Standard' ,'Express')
group by 1;

-- Q5: Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers

select subscription_status,
	count(customer_id) as id,
	round(avg(purchase_amount),2) as Avg_purchase,
	round(sum(purchase_amount),2) as revenue
from customer
group by 1
order by 2,3 desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
	concat(
			round(
				(sum(case when discount_applied ='yes' then 1 else 0 end)/count(customer_id))*100,2),'%') as percentage
from customer
group by 1
order by 2 desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with cte as(
select customer_id,previous_purchases,
case
	when previous_purchases =1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
end as customer_segment
from customer)

select customer_segment,count(*) as No_of_customer
from cte
group by 1;

-- Q8. What are the top 3 most purchased products within each category? 
with count_item as(
select category,
item_purchased,
count(customer_id) as total_order,
row_number() over(partition by category order by count(customer_id) desc) as rnk
from customer
group by 1,2)

select rnk,category,item_purchased,total_order
from count_item
where rnk <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by 1;

-- Q10. What is the revenue contribution of each age group? 
select age_group,
sum(purchase_amount) as revenue
from customer
group by 1
order by 2 desc;

